query replies($after: String, $before: String, $excludePins: Boolean, $limit: Int!, $offset: Int, $orderBy: PostListOrderByEnum, $postId: ID!, $reverse: Boolean) {
  replies(
    after: $after
    before: $before
    excludePins: $excludePins
    limit: $limit
    offset: $offset
    orderBy: $orderBy
    postId: $postId
    reverse: $reverse
  ) {
    totalCount
    nodes {
        id
        mappingFields {
            key
            type
            value
        }
        repliedToId
        replies(limit: 100, reverse: true, orderBy: createdAt) {
            nodes {
                id
                slug
                shortContent
                createdAt
                publishedAt
                ownerId
                status
                repliedToId
                title
                description
            }
            pageInfo {
                endCursor
                hasNextPage
            }
            totalCount
        }
        publishedAt
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}