query searchPosts($after: String, $filters: FiltersInput, $limit: Int!, $query: String!, $searchConfig: SearchConfigInput) {
  searchPosts(
    after: $after
    filters: $filters
    limit: $limit
    query: $query
    searchConfig: $searchConfig
  ) {
    nodes {
      id
      title
      description
      totalRepliesCount
      relativeUrl
      lastActivityAt
      publishedAt
      space {
        name
      }
      url
    }
    pageInfo {
      endCursor
      hasNextPage
    }
    totalCount
  }
}